version: 2.1

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "poetry.lock" }}
    - run:
        name: install dependencies
        command: |
            sudo apt install poppler-utils
            sudo apt install yarnpkg
            sudo ln -sf /usr/bin/yarnpkg /usr/bin/yarn
            sudo yarn global add less
            pip install --user poetry tox codecov "coverage<5"
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "poetry.lock" }}

jobs:
  py38:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38
  py39:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV=py39
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          - TOXENV=lint
          - UPLOAD_COVERAGE=0
  safety:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          - TOXENV=safety

workflows:
  version: 2
  test:
    jobs:
      - py38
      - py39
      - lint
      - safety
